# Generated by Django 4.2.11 on 2024-04-20 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_rename_caption_post_content_rename_user_post_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="juza",
            field=models.CharField(
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                    ("11", "11"),
                ],
                default="1",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="shiek",
            field=models.CharField(
                choices=[("mohamend", "mohamend")], default="mohamend", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="surah",
            field=models.CharField(
                choices=[("Albqara", "Albqara")], default="Albqara", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
