# Generated by Django 4.2.11 on 2024-04-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_item_alter_post_content_alter_post_file_likedislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likedislike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes_dislikes",
                to="user.post",
            ),
        ),
    ]
